# Use the TypeScript parser and plugin
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"

# Set the environment
env:
  node: true

# Specify the file extensions
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"

# Specify the rules
rules:
  # Indent with 2 spaces
  indent: ["error", 2]

  # Use double quotes for strings
  quotes: ["error", "double"]

  # Require semicolons at the end of statements
  semi: ["error", "always"]

  # Disallow unused variables
  "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_" }]

  # Enforce consistent return types
  "@typescript-eslint/explicit-function-return-type": ["error", { "allowExpressions": true }]

  # Enforce consistent naming conventions
  "@typescript-eslint/naming-convention":
    - "error"
    - {
        "selector": "default",
        "format": ["camelCase"]
      }
    - {
        "selector": "variableLike",
        "format": ["camelCase", "PascalCase", "UPPER_CASE"]
      }
    - {
        "selector": "typeLike",
        "format": ["PascalCase"]
      }

# Specify the parser options
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  project: ./tsconfig.json
